import type { Metadata } from "next";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
import  './global.css'
export const metadata: Metadata = {
  title: "Zyok| Forms Made Easy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="bg-white" lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
